### ISSUE TITLE
Blurry text in dropdown

### ISSUE THREAD

**Issue by AdamTReineke** [returntocorp/secarta-extension#117]
The current styles make the drop down on the right side of my screenshot blurry.

![blur-with-transform](https://user-images.githubusercontent.com/518655/46442644-2eed0900-c71f-11e8-9c7a-dfc6b5b8be50.PNG)

When I just use top and left and remove the transform, it gets better. (See changed styles on the left in the dev tools.)

![no-blur-with-topleft](https://user-images.githubusercontent.com/518655/46442646-2eed0900-c71f-11e8-864b-d79b64841b22.PNG)

Repro in Chrome on Windows at 1x scaling (no high DPI).

**Comment by lediur** [comment]
Hey Adam, thanks for reporting this issue. The dropdown list uses https://github.com/palantir/blueprint, which in turn uses https://github.com/FezVrasta/popper.js for their popover implementation, so we'll dig into those to see if there's a way to make the CSS changes you proposed.

Which version of Chrome are you seeing this issue in? On Chrome 69 and Windows (17763.1), I'm not sure if I'm seeing the same blur.

![image](https://user-images.githubusercontent.com/1077648/46443076-d880ca00-c720-11e8-95ee-c4dfa5483bf2.png)

This is on a 100% scaling in a multi-monitor multi-DPI configuration (1x 200% scaling 4K laptop screen, 2x 100% 1080p external monitor)

Also, are you able to reproduce the issue on other browsers? We currently use Chrome on Windows and Mac, Firefox on Windows and Linux, and Microsoft Edge as well during dev so if you're also able to try it out on other browsers that would be super helpful.

**Comment by AdamTReineke** [comment]
Chrome 69.0.3497.100

Server 2016 (Version 1607, OS Build 14393.2485)

Multi-monitor, 2560x1440

Haven't looked into other browsers yet.

**Comment by lediur** [comment]
No worries! I think you've stumbled on a Chrome issue with GPU acceleration and 3D transforms, like `translate3d`. Others have reported similar issues, e.g. https://stackoverflow.com/questions/8024061/webkit-blurry-text-with-css-scale-translate3d

Let us know if you see similar issues in the future and we can take a look 🌞
