### ISSUE TITLE
Closing Preflight dialog action isn't "remembered"

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/secarta-extension#122]
When Preflight dialogs are closed on project pages, the action doesn't persist across refreshes. The expectation from users has been that the action would be remembered, and it ends up introducing friction into the people's workflow (some have reported that they'll always "x" out of the dialog in the "Preflight not found" case).

**Comment by lediur** [comment]
would rather add a "Don't show this again" button

**Comment by tnarla** [comment]
https://github.com/returntocorp/secarta-extension/pull/158
