### ISSUE TITLE
Errors in loading Preflight in Chrome extension are shown as [Object object]

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [returntocorp/secarta-extension#134]
## What happened?
Visiting https://github.com/palantir/tslint, you get this:

Couldn't load Preflight. Check that `api.secarta.io` is whitelisted in your browser.

```text
[object Object]
{"gitUrl":"https://github.com/palantir/tslint"}
```

![image](https://user-images.githubusercontent.com/3335181/46962924-5c687980-d072-11e8-86b6-799cd941324d.png)

## What did you expect to happen?
Normal TypeScript repo.

## To reproduce

1. Go to https://github.com/palantir/tslint
2. Click 'See more'
3. See error

## Specs
- OS: Windows 10 1803
- Browser: Chrome 69

**Comment by dlukeomalley** [comment]
@JoshuaKGoldberg We resolved the issue for tslint, should have results now: https://github.com/palantir/tslint

**Comment by lediur** [comment]
We were stringifying all errors but only some error messages actually have a way to `toString`. I got rid of that call so the `[object Object]` things should disappear
