### ISSUE TITLE
Don't complain about "eval" on .d.ts files

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [returntocorp/secarta-extension#146]
## What happened?

![image](https://user-images.githubusercontent.com/3335181/47402510-85a19d80-d735-11e8-9464-2b481ea541de.png)

https://github.com/Microsoft/tslint-microsoft-contrib/blob/894dc6b781c05edbbde57453abbd49c86a374dd8/typings/node.d.ts#L556

## What did you expect to happen?

`eval` is only a Bad Thing when the global is used, not in a type definition.

## To reproduce
1. Go to https://github.com/Microsoft/tslint-microsoft-contrib/
2. See the errors list
3. Go to the complaint under `typings/`

**Comment by JoshuaKGoldberg** [comment]
If you're looking for style complaints, like using the right constructs to define the code, https://github.com/Microsoft/dtslint/blob/master/dtslint.json is a reasonable base template.

If you're looking for serious issues such as security vulnerabilities, then no, think type definitions don't seem like the right places to look.

My two cents: probably not worth it to look at the type definitions.

**Comment by dlukeomalley** [comment]
@JoshuaKGoldberg We rolled out some new behind-the-scenes infrastructure and API improvements today which appear to have resolved this issue. You should also see far fewer projects with missing results.

Closing out. Please reopen if you're seeing something different. 🙏
