### ISSUE TITLE
Broken GitHub styling because of Preflight

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/secarta-extension#154]
With Preflight installed:
![image](https://user-images.githubusercontent.com/605906/47607699-24e5bf80-d9d8-11e8-9279-886855202fbc.png)

Without Preflight installed:
![image](https://user-images.githubusercontent.com/605906/47607702-2d3dfa80-d9d8-11e8-8575-3c5319eee9fa.png)

**Comment by lediur** [comment]
Doesn't look like that on my machine:

![image](https://user-images.githubusercontent.com/1077648/47663547-86ce3280-db5a-11e8-99b7-7b45738486ac.png)

**Comment by tnarla** [comment]
For some reason, the production build of 1.11.0 does not have the issue whereas the dev build of 1.11.0 (the latest release build) **does** have the issue. Might be something very obscure and hidden. Can keep digging after looking at the other issues.

**Comment by dlukeomalley** [comment]
Closing out for now. We'll add this to our QA/tests list and monitor for future regressions.
