### ISSUE TITLE
Expected error state, got full headsup

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/secarta-extension#157]
https://github.com/Kikobeats/react-clap-button

I expected an error state given that every endpoint returned a 404, except for `package/`, which returns empty.

Is this an API change or a UI bug?

![image](https://user-images.githubusercontent.com/605906/47823415-761de800-dd25-11e8-973d-8dd756741800.png)

**Comment by lediur** [comment]
UI bug I believe since we only show the missing state if _everything_ is 404. If `package/` is returning information (even if that information is blank) then the state won't be triggered

**Comment by dlukeomalley** [comment]
I think this is API; empty list to me means "we couldn't find any packages", which feels like a `404` condition.

Let's kick this over to @DrewDennison or @ulziibay.

**Comment by dlukeomalley** [comment]
Fixed with a backend change!
