### ISSUE TITLE
Finding shown on package.json incorrectly

### ISSUE THREAD

**Issue by ulziibay** [returntocorp/secarta-extension#186]
## What happened?
https://github.com/wmonk/create-react-app/blob/next/package.json#L42 shows finding incorrectly.

## What did you expect to happen?
No finding on package.json file

## To reproduce

1. Go to https://github.com/wmonk/create-react-app
2. Click on 'package.json'
3. Scroll down to 'bottom of the page'

## Specs
- OS: [e.g. macOS high sierra]
- Browser: [e.g. Chrome 70]
- Screen size (if appropriate): full
<img width="2316" alt="screen shot 2018-11-13 at 2 58 32 pm" src="https://user-images.githubusercontent.com/1626382/48448770-eb8dad80-e754-11e8-9a43-5683423d865f.png">

**Comment by dlukeomalley** [comment]
@ulziibay I'm unable to reproduce this bug. Have you seen it since you've filed this issue and/or are you still able to reproduce it?

**Comment by ulziibay** [comment]
@dlukeomalley: nope I cannot repro. Closing!
