### ISSUE TITLE
Red state and the itemized checklist don't match

### ISSUE THREAD

**Issue by daghan** [returntocorp/secarta-extension#193]
## What happened?
When looking at this: https://github.com/dominictarr/event-stream, I see that we know have a "red" opinion for this package. Yet all the checklist are either green (except for one "npm install hook" warning/info)

## What did you expect to happen?
I would have thought that the known vulnerabilities checklist item to be red. 

## To reproduce
Go here and expand:
https://github.com/dominictarr/event-stream

## Specs
- OS: macOS Mojave
- Browser: Chrome 70

![image](https://user-images.githubusercontent.com/433961/49124083-e27dff80-f26f-11e8-9d02-9eeed6015193.png)

**Comment by dlukeomalley** [comment]
@daghan Thanks for the filing this. This will be addressed by #195 💪
