### ISSUE TITLE
Extension doesn't set uninstall URL properly

### ISSUE THREAD

**Issue by lediur** [returntocorp/secarta-extension#64]
The WebExtension standard allows extensions to set an uninstall URL to display to the user when they uninstall the extension ([MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/setUninstallURL), [Chrome](https://developer.chrome.com/extensions/runtime#method-setUninstallURL)). We're calling that in `background.js`, but apparently we're doing it wrong because the page doesn't appear on uninstall.

**Comment by dlukeomalley** [comment]
Tested on `1.10.0` and didn't get the uninstall survey. Let's re-surface this one and try to vanquish it for good.

**Comment by lediur** [comment]
Reproduced as working on Firefox and Edge. Going to see what's up with Chrome

**Comment by lediur** [comment]
Found the issue. Thanks Chrome

![image](https://user-images.githubusercontent.com/1077648/46552002-2a932e00-c88e-11e8-8da2-9e8bbaf3eed0.png)
