### ISSUE TITLE
Khan/KaTex incorrectly labeled as archived in preflight

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/secarta-extension#69]
https://github.com/Khan/KaTeX

GitHub shows the project as being recently active, but we mark it as archived.

![image](https://user-images.githubusercontent.com/605906/46084025-8d324e80-c157-11e8-8690-0ada143a9315.png)

**Comment by dlukeomalley** [comment]
Another example of incorrectly marked as archived: https://github.com/expressjs/express

![image](https://user-images.githubusercontent.com/605906/46105070-e4e9ad80-c189-11e8-8d62-9b2b33cd5522.png)

**Comment by ulziibay** [comment]
@dlukeomalley found this logical error: https://github.com/returntocorp/echelon-backend/pull/1970
