### ISSUE TITLE
Preflight is empty for most GitHub projects (because not npm or JS)

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/secarta-extension#72]
Tracking ticket to revisit when/how we show that a project is unsupported. Looking through usage logs I believe this triggers frequently for folks.

<img width="1000" alt="screen shot 2018-09-26 at 7 08 47 am" src="https://user-images.githubusercontent.com/605906/46085506-0a12f780-c15b-11e8-8ca6-fb4048599588.png">

**Comment by ulziibay** [comment]
Do we log when we show this and when user logs "Let us know!"? It would great to pull the data to see if there is demand for other languages etc.

**Comment by dlukeomalley** [comment]
Yup, we do in the next release! Keeping this here because we may not want to show anything on non-JS projects.

**Comment by lediur** [comment]
Is this resolved by #119?

**Comment by dlukeomalley** [comment]
This is partially addressed by #119. I'd like to go further though with this design task, answering:

1. For projects that contain no JavaScript or TypeScript, should we show anything from Preflight?
2. For projects that are not published to npm, but have JS/TS, should we show results or the ability to analyze the project?

**Comment by dlukeomalley** [comment]
This has been addressed by giving users the ability to permanently disable preflight on non JS/TS projects and our decision to exclusively support projects that are published to npm.
