### ISSUE TITLE
Permissions aren't explorable

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/secarta-extension#74]
Example project: https://github.com/bripkens/connect-history-api-fallback

I'd like to be able to click through to the specific line / finding for permissions if present.

![image](https://user-images.githubusercontent.com/605906/46105102-064a9980-c18a-11e8-9087-60a6f16d7d14.png)

**Comment by ulziibay** [comment]
The API returns it. I think we just did not invest in making it surfacable as its 2/1000 repos that have it https://api.secarta.io/v1/permissions/github.com/bripkens/connect-history-api-fallback

**Comment by dlukeomalley** [comment]
I'll pick up this one tomorrow. Will be a mix of BE/FE - I want to update the `permissions/` API to return findings in the same format as the `findings/`endpoint, and reuse the findings component.
